xmsmesh: /home/conan/xmsmesh/meshing/MeMultiPolyTo2dm.cpp File Reference
MeMultiPolyTo2dm.cpp File Reference
#include <xmsmesh/meshing/MeMultiPolyTo2dm.h>
#include <array>
#include <fstream>
#include <sstream>
#include <cmath>
#include <boost/format.hpp>
#include <xmscore/misc/StringUtil.h>
#include <xmscore/misc/XmConst.h>
#include <xmscore/misc/XmError.h>
#include <xmscore/misc/XmLog.h>
#include <xmscore/points/pt.h>
#include <xmscore/stl/vector.h>
#include <xmsinterp/geometry/geoms.h>
#include <xmsmesh/meshing/MeMultiPolyMesher.h>
#include <xmsmesh/meshing/MeMultiPolyMesherIo.h>
#include <xmscore/misc/carray.h>
#include <xmsmesh/meshing/MeMultiPolyTo2dm.t.h>
#include <xmscore/testing/TestTools.h>
#include <xmsmesh/tutorial/TutMeshing.t.h>
Classes
class xms::MeMultiPolyTo2dmImpl
Creates a VTK Unstructured Grid from polygons.
Functions
static void xms::iSortCellsForTesting (MeMultiPolyMesherIo &a_io)
sorts the cells based so that the node with the smallest number will be first and then the cells are sorted.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under the xmsng Software License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at http://www.aquaveo.com/xmsng/LICENSE_1_0.txt)
Definition in file MeMultiPolyTo2dm.cpp.
Function Documentation
iSortCellsForTesting()
static void xms::iSortCellsForTesting (MeMultiPolyMesherIo & a_io) static
sorts the cells based so that the node with the smallest number will be first and then the cells are sorted.
Parameters
[in] a_io MeMultiPolyMesherIo class that has an output mesh
Definition at line 82 of file MeMultiPolyTo2dm.cpp.
References xms::iSortCellsForTesting(), and xms::MeMultiPolyMesherIo::m_cells.
Referenced by xms::iSortCellsForTesting(), and xms::MeMultiPolyTo2dmImpl::Write2dm().