xmsmesh: /home/conan/xmsmesh/tutorial/TutMeshing.t.h File Reference
TutMeshing.t.h File Reference
#include <cxxtest/TestSuite.h>
#include <xmscore/stl/vector.h>
Classes
class TutMeshingIntermediateTests
Class for testing meshing functionality.
class TutRedistributionIntermediateTests
Class for testing polyline/polygon point redistribution.
Functions
bool xms::tutReadMeshIoFromFile (const std::string &a_fname, MeMultiPolyMesherIo &a_io)
helper function to read MeMultiPolyMesherIo
bool xms::tutReadPolygons (const std::string &a_fname, VecPt3d2d &a_outside, VecPt3d3d &a_inside)
helper function to read polygons from a text file
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file TutMeshing.t.h.
Function Documentation
tutReadMeshIoFromFile()
bool xms::tutReadMeshIoFromFile (const std::string & a_fname, MeMultiPolyMesherIo & a_io)
helper function to read MeMultiPolyMesherIo
Parameters
a_fname File name where the polygon is stored
a_io MeMultiPolyMesherIo class that is filled by this function
Returns
true if the file was read with no errors
Definition at line 64 of file TutMeshing.cpp.
References gmPolygonArea(), xms::MePolyInput::m_bias, xms::MeMultiPolyMesherIo::m_checkTopology, xms::MePolyInput::m_constSizeBias, xms::MePolyInput::m_constSizeFunction, xms::MeRefinePoint::m_createMeshPoint, xms::MePolyInput::m_elevFunction, xms::MePolyInput::m_insidePolys, xms::MePolyInput::m_outPoly, xms::MePolyInput::m_polyCorners, xms::MeMultiPolyMesherIo::m_polys, xms::MeRefinePoint::m_pt, xms::MeMultiPolyMesherIo::m_refPts, xms::MePolyInput::m_relaxationMethod, xms::MeMultiPolyMesherIo::m_returnCellPolygons, xms::MePolyInput::m_seedPoints, xms::MeRefinePoint::m_size, xms::MePolyInput::m_sizeFunction, xms::InterpIdw::New(), xms::InterpLinear::New(), xms::TrTriangulator::Triangulate(), xms::tutReadMeshIoFromFile(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by xms::tutReadMeshIoFromFile(), and xms::tutReadPolygons().
tutReadPolygons()
bool xms::tutReadPolygons (const std::string & a_fname, VecPt3d2d & a_outside, VecPt3d3d & a_inside)
helper function to read polygons from a text file
Parameters
a_fname File name where the polygon is stored
a_outside Vector of locations for the definition of the outside of the polygon.
a_inside 2d vector of locations to define multiple inside polygons
Returns
true if the file was read without any errors
Definition at line 220 of file TutMeshing.cpp.
References xms::MeMultiPolyMesherIo::m_polys, xms::tutReadMeshIoFromFile(), and xms::tutReadPolygons().
Referenced by MeMultiPolyTo2dmIntermediateTests::testCasePatch6(), MeMultiPolyTo2dmIntermediateTests::testCasePaveConstSizeTransition(), and xms::tutReadPolygons().