var annotated_dup =
[
    [ "xms", null, [
      [ "MeBadQuadRemover", "classxms_1_1_me_bad_quad_remover.html", "classxms_1_1_me_bad_quad_remover" ],
      [ "MeEdge", "structxms_1_1_me_edge.html", "structxms_1_1_me_edge" ],
      [ "MeIntersectPolys", "classxms_1_1_me_intersect_polys.html", "classxms_1_1_me_intersect_polys" ],
      [ "MeMultiPolyMesher", "classxms_1_1_me_multi_poly_mesher.html", "classxms_1_1_me_multi_poly_mesher" ],
      [ "MeMultiPolyMesherImpl", "classxms_1_1_me_multi_poly_mesher_impl.html", "classxms_1_1_me_multi_poly_mesher_impl" ],
      [ "MeMultiPolyMesherIo", "classxms_1_1_me_multi_poly_mesher_io.html", "classxms_1_1_me_multi_poly_mesher_io" ],
      [ "MeMultiPolyTo2dm", "classxms_1_1_me_multi_poly_to2dm.html", "classxms_1_1_me_multi_poly_to2dm" ],
      [ "MeMultiPolyTo2dmImpl", "classxms_1_1_me_multi_poly_to2dm_impl.html", "classxms_1_1_me_multi_poly_to2dm_impl" ],
      [ "MePolyCleaner", "classxms_1_1_me_poly_cleaner.html", "classxms_1_1_me_poly_cleaner" ],
      [ "MePolyCleanerImpl", "classxms_1_1_me_poly_cleaner_impl.html", "classxms_1_1_me_poly_cleaner_impl" ],
      [ "MePolyInput", "classxms_1_1_me_poly_input.html", "classxms_1_1_me_poly_input" ],
      [ "MePolyMesher", "classxms_1_1_me_poly_mesher.html", "classxms_1_1_me_poly_mesher" ],
      [ "MePolyMesherImpl", "classxms_1_1_me_poly_mesher_impl.html", "classxms_1_1_me_poly_mesher_impl" ],
      [ "MePolyOffsetter", "classxms_1_1_me_poly_offsetter.html", "classxms_1_1_me_poly_offsetter" ],
      [ "MePolyOffsetterImpl", "classxms_1_1_me_poly_offsetter_impl.html", "classxms_1_1_me_poly_offsetter_impl" ],
      [ "MePolyOffsetterOutput", "classxms_1_1_me_poly_offsetter_output.html", "classxms_1_1_me_poly_offsetter_output" ],
      [ "MePolyPatcher", "classxms_1_1_me_poly_patcher.html", "classxms_1_1_me_poly_patcher" ],
      [ "MePolyPatcherImpl", "classxms_1_1_me_poly_patcher_impl.html", "classxms_1_1_me_poly_patcher_impl" ],
      [ "MePolyPaverToMeshPts", "classxms_1_1_me_poly_paver_to_mesh_pts.html", "classxms_1_1_me_poly_paver_to_mesh_pts" ],
      [ "MePolyPts", "classxms_1_1_me_poly_pts.html", "classxms_1_1_me_poly_pts" ],
      [ "MePolyRedistributePts", "classxms_1_1_me_poly_redistribute_pts.html", "classxms_1_1_me_poly_redistribute_pts" ],
      [ "MePolyRedistributePtsCurvature", "classxms_1_1_me_poly_redistribute_pts_curvature.html", "classxms_1_1_me_poly_redistribute_pts_curvature" ],
      [ "MePolyRedistributePtsCurvatureImpl", "classxms_1_1_me_poly_redistribute_pts_curvature_impl.html", "classxms_1_1_me_poly_redistribute_pts_curvature_impl" ],
      [ "MePolyRedistributePtsImpl", "classxms_1_1_me_poly_redistribute_pts_impl.html", "classxms_1_1_me_poly_redistribute_pts_impl" ],
      [ "MeQuadBlossom", "classxms_1_1_me_quad_blossom.html", "classxms_1_1_me_quad_blossom" ],
      [ "MeRefinePoint", "classxms_1_1_me_refine_point.html", "classxms_1_1_me_refine_point" ],
      [ "MeRefinePtsToPolys", "classxms_1_1_me_refine_pts_to_polys.html", "classxms_1_1_me_refine_pts_to_polys" ],
      [ "MeRefinePtsToPolysImpl", "classxms_1_1_me_refine_pts_to_polys_impl.html", "classxms_1_1_me_refine_pts_to_polys_impl" ],
      [ "MeRelaxer", "classxms_1_1_me_relaxer.html", "classxms_1_1_me_relaxer" ],
      [ "MeRelaxerImpl", "classxms_1_1_me_relaxer_impl.html", "classxms_1_1_me_relaxer_impl" ],
      [ "MeWeightMatcher", "classxms_1_1_me_weight_matcher.html", "classxms_1_1_me_weight_matcher" ],
      [ "SegmentLocation", "structxms_1_1_segment_location.html", "structxms_1_1_segment_location" ],
      [ "SmoothIo", "classxms_1_1_smooth_io.html", "classxms_1_1_smooth_io" ]
    ] ],
    [ "MeBadQuadRemoverUnitTests", "class_me_bad_quad_remover_unit_tests.html", "class_me_bad_quad_remover_unit_tests" ],
    [ "MeIntersectPolysUnitTests", "class_me_intersect_polys_unit_tests.html", "class_me_intersect_polys_unit_tests" ],
    [ "MeMeshUtilsUnitTests", "class_me_mesh_utils_unit_tests.html", "class_me_mesh_utils_unit_tests" ],
    [ "MeMultiPolyMesherUnitTests", "class_me_multi_poly_mesher_unit_tests.html", "class_me_multi_poly_mesher_unit_tests" ],
    [ "MeMultiPolyTo2dmIntermediateTests", "class_me_multi_poly_to2dm_intermediate_tests.html", "class_me_multi_poly_to2dm_intermediate_tests" ],
    [ "MeMultiPolyTo2dmUnitTests", "class_me_multi_poly_to2dm_unit_tests.html", "class_me_multi_poly_to2dm_unit_tests" ],
    [ "MePolyCleanerUnitTests", "class_me_poly_cleaner_unit_tests.html", "class_me_poly_cleaner_unit_tests" ],
    [ "MePolyMesherUnitTests", "class_me_poly_mesher_unit_tests.html", "class_me_poly_mesher_unit_tests" ],
    [ "MePolyOffsetterUnitTests", "class_me_poly_offsetter_unit_tests.html", "class_me_poly_offsetter_unit_tests" ],
    [ "MePolyPatcherUnitTests", "class_me_poly_patcher_unit_tests.html", "class_me_poly_patcher_unit_tests" ],
    [ "MePolyPaverToMeshPtsUnitTests", "class_me_poly_paver_to_mesh_pts_unit_tests.html", "class_me_poly_paver_to_mesh_pts_unit_tests" ],
    [ "MePolyRedistributePtsCurvatureIntermediateTests", "class_me_poly_redistribute_pts_curvature_intermediate_tests.html", "class_me_poly_redistribute_pts_curvature_intermediate_tests" ],
    [ "MePolyRedistributePtsCurvatureUnitTests", "class_me_poly_redistribute_pts_curvature_unit_tests.html", "class_me_poly_redistribute_pts_curvature_unit_tests" ],
    [ "MePolyRedistributePtsUnitTests", "class_me_poly_redistribute_pts_unit_tests.html", "class_me_poly_redistribute_pts_unit_tests" ],
    [ "MeQuadBlossomUnitTests", "class_me_quad_blossom_unit_tests.html", "class_me_quad_blossom_unit_tests" ],
    [ "MeRefinePtsToPolysUnitTests", "class_me_refine_pts_to_polys_unit_tests.html", "class_me_refine_pts_to_polys_unit_tests" ],
    [ "MeRelaxerUnitTests", "class_me_relaxer_unit_tests.html", "class_me_relaxer_unit_tests" ],
    [ "MeWeightMatcherUnitTests", "class_me_weight_matcher_unit_tests.html", "class_me_weight_matcher_unit_tests" ],
    [ "TutMeshingIntermediateTests", "class_tut_meshing_intermediate_tests.html", "class_tut_meshing_intermediate_tests" ],
    [ "TutRedistributionIntermediateTests", "class_tut_redistribution_intermediate_tests.html", "class_tut_redistribution_intermediate_tests" ]
];