var annotated =
[
    [ "python", null, [
      [ "meshing", null, [
        [ "MeMeshUtils_pyt", "namespacepython_1_1meshing_1_1_me_mesh_utils__pyt.html", "namespacepython_1_1meshing_1_1_me_mesh_utils__pyt" ],
        [ "MeMultiPolyMesher_pyt", "namespacepython_1_1meshing_1_1_me_multi_poly_mesher__pyt.html", "namespacepython_1_1meshing_1_1_me_multi_poly_mesher__pyt" ],
        [ "MeMultiPolyMesherIo_pyt", "namespacepython_1_1meshing_1_1_me_multi_poly_mesher_io__pyt.html", "namespacepython_1_1meshing_1_1_me_multi_poly_mesher_io__pyt" ],
        [ "MeMultiPolyTo2dm_pyt", "namespacepython_1_1meshing_1_1_me_multi_poly_to2dm__pyt.html", "namespacepython_1_1meshing_1_1_me_multi_poly_to2dm__pyt" ],
        [ "MePolyMesher_pyt", "namespacepython_1_1meshing_1_1_me_poly_mesher__pyt.html", "namespacepython_1_1meshing_1_1_me_poly_mesher__pyt" ],
        [ "MePolyRedistributePts_pyt", "namespacepython_1_1meshing_1_1_me_poly_redistribute_pts__pyt.html", "namespacepython_1_1meshing_1_1_me_poly_redistribute_pts__pyt" ]
      ] ],
      [ "misc", null, null ]
    ] ],
    [ "xms", null, [
      [ "MeIntersectPolys", "classxms_1_1_me_intersect_polys.html", "classxms_1_1_me_intersect_polys" ],
      [ "MePolyCleanerImpl", "classxms_1_1_me_poly_cleaner_impl.html", "classxms_1_1_me_poly_cleaner_impl" ],
      [ "MePolyCleaner", "classxms_1_1_me_poly_cleaner.html", "classxms_1_1_me_poly_cleaner" ],
      [ "MePolyOffsetterImpl", "classxms_1_1_me_poly_offsetter_impl.html", "classxms_1_1_me_poly_offsetter_impl" ],
      [ "MePolyOffsetterOutput", "classxms_1_1_me_poly_offsetter_output.html", "classxms_1_1_me_poly_offsetter_output" ],
      [ "MePolyOffsetter", "classxms_1_1_me_poly_offsetter.html", "classxms_1_1_me_poly_offsetter" ],
      [ "MePolyPatcherImpl", "classxms_1_1_me_poly_patcher_impl.html", "classxms_1_1_me_poly_patcher_impl" ],
      [ "MePolyPatcher", "classxms_1_1_me_poly_patcher.html", "classxms_1_1_me_poly_patcher" ],
      [ "MePolyPaverToMeshPts", "classxms_1_1_me_poly_paver_to_mesh_pts.html", "classxms_1_1_me_poly_paver_to_mesh_pts" ],
      [ "MePolyPts", "classxms_1_1_me_poly_pts.html", "classxms_1_1_me_poly_pts" ],
      [ "MeRefinePtsToPolysImpl", "classxms_1_1_me_refine_pts_to_polys_impl.html", "classxms_1_1_me_refine_pts_to_polys_impl" ],
      [ "MeRefinePtsToPolys", "classxms_1_1_me_refine_pts_to_polys.html", "classxms_1_1_me_refine_pts_to_polys" ],
      [ "MeRelaxerImpl", "classxms_1_1_me_relaxer_impl.html", "classxms_1_1_me_relaxer_impl" ],
      [ "MeRelaxer", "classxms_1_1_me_relaxer.html", "classxms_1_1_me_relaxer" ],
      [ "SmoothIo", "classxms_1_1_smooth_io.html", "classxms_1_1_smooth_io" ],
      [ "MeMultiPolyMesherImpl", "classxms_1_1_me_multi_poly_mesher_impl.html", "classxms_1_1_me_multi_poly_mesher_impl" ],
      [ "SegmentLocation", "structxms_1_1_segment_location.html", "structxms_1_1_segment_location" ],
      [ "MeMultiPolyMesher", "classxms_1_1_me_multi_poly_mesher.html", "classxms_1_1_me_multi_poly_mesher" ],
      [ "MePolyInput", "classxms_1_1_me_poly_input.html", "classxms_1_1_me_poly_input" ],
      [ "MeRefinePoint", "classxms_1_1_me_refine_point.html", "classxms_1_1_me_refine_point" ],
      [ "MeMultiPolyMesherIo", "classxms_1_1_me_multi_poly_mesher_io.html", "classxms_1_1_me_multi_poly_mesher_io" ],
      [ "MeMultiPolyTo2dmImpl", "classxms_1_1_me_multi_poly_to2dm_impl.html", "classxms_1_1_me_multi_poly_to2dm_impl" ],
      [ "MeMultiPolyTo2dm", "classxms_1_1_me_multi_poly_to2dm.html", "classxms_1_1_me_multi_poly_to2dm" ],
      [ "MePolyMesherImpl", "classxms_1_1_me_poly_mesher_impl.html", "classxms_1_1_me_poly_mesher_impl" ],
      [ "MePolyMesher", "classxms_1_1_me_poly_mesher.html", "classxms_1_1_me_poly_mesher" ],
      [ "MePolyRedistributePtsImpl", "classxms_1_1_me_poly_redistribute_pts_impl.html", "classxms_1_1_me_poly_redistribute_pts_impl" ],
      [ "MePolyRedistributePts", "classxms_1_1_me_poly_redistribute_pts.html", "classxms_1_1_me_poly_redistribute_pts" ]
    ] ],
    [ "MeIntersectPolysUnitTests", "class_me_intersect_polys_unit_tests.html", "class_me_intersect_polys_unit_tests" ],
    [ "MeMeshUtilsUnitTests", "class_me_mesh_utils_unit_tests.html", "class_me_mesh_utils_unit_tests" ],
    [ "MeMultiPolyMesherUnitTests", "class_me_multi_poly_mesher_unit_tests.html", "class_me_multi_poly_mesher_unit_tests" ],
    [ "MeMultiPolyTo2dmIntermediateTests", "class_me_multi_poly_to2dm_intermediate_tests.html", "class_me_multi_poly_to2dm_intermediate_tests" ],
    [ "MeMultiPolyTo2dmUnitTests", "class_me_multi_poly_to2dm_unit_tests.html", "class_me_multi_poly_to2dm_unit_tests" ],
    [ "MePolyCleanerUnitTests", "class_me_poly_cleaner_unit_tests.html", "class_me_poly_cleaner_unit_tests" ],
    [ "MePolyMesherUnitTests", "class_me_poly_mesher_unit_tests.html", "class_me_poly_mesher_unit_tests" ],
    [ "MePolyOffsetterUnitTests", "class_me_poly_offsetter_unit_tests.html", "class_me_poly_offsetter_unit_tests" ],
    [ "MePolyPatcherUnitTests", "class_me_poly_patcher_unit_tests.html", "class_me_poly_patcher_unit_tests" ],
    [ "MePolyPaverToMeshPtsUnitTests", "class_me_poly_paver_to_mesh_pts_unit_tests.html", "class_me_poly_paver_to_mesh_pts_unit_tests" ],
    [ "MePolyRedistributePtsUnitTests", "class_me_poly_redistribute_pts_unit_tests.html", "class_me_poly_redistribute_pts_unit_tests" ],
    [ "MeRefinePtsToPolysUnitTests", "class_me_refine_pts_to_polys_unit_tests.html", "class_me_refine_pts_to_polys_unit_tests" ],
    [ "MeRelaxerUnitTests", "class_me_relaxer_unit_tests.html", "class_me_relaxer_unit_tests" ],
    [ "TutMeshingIntermediateTests", "class_tut_meshing_intermediate_tests.html", "class_tut_meshing_intermediate_tests" ]
];