xmsmesh: xms::MePolyRedistributePts Class Reference
xms::MePolyRedistributePts Class Reference
Redistributes the point locations on a polygon based on a size function.
#include <MePolyRedistributePts.h>
Public Member Functions
virtual ~MePolyRedistributePts ()
destructor
Static Public Member Functions
static BSHP< MePolyRedistributePts > New ()
Creates an instance of this class.
Protected Member Functions
MePolyRedistributePts ()
constructor
Detailed Description
Redistributes the point locations on a polygon based on a size function.
See also
MePolyRedistributePtsImpl
Definition at line 28 of file MePolyRedistributePts.h.
Member Function Documentation
New()
BSHP< MePolyRedistributePts > xms::MePolyRedistributePts::New () static
Creates an instance of this class.
Returns
MePolyRedistributePts
Definition at line 185 of file MePolyRedistributePts.cpp.
Referenced by xms::MePolyMesherImpl::MeshIt(), TutRedistributionIntermediateTests::test_Example_Redistribute_Curvature(), TutRedistributionIntermediateTests::test_Example_Redistribute_Polygon_Curvature(), TutRedistributionIntermediateTests::test_Example_Redistribute_SizeFunction(), TutRedistributionIntermediateTests::test_Example_SimplePolygon_Redistribute(), MePolyRedistributePtsUnitTests::testCreateClass(), MeRelaxerUnitTests::testNewLocationIsValid(), MeRelaxerUnitTests::testSpringRelaxSetup(), MeRelaxerUnitTests::testSpringRelaxSetup2(), MeRelaxerUnitTests::testSpringRelaxSinglePoint(), MeRelaxerUnitTests::testSpringRelaxSinglePoint2(), and MeRelaxerUnitTests::testSpringRelaxSinglePoint3().
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/meshing/MePolyRedistributePts.h
/home/conan/xmsmesh/meshing/MePolyRedistributePts.cpp