xmsmesh: MePolyRedistributePtsCurvatureUnitTests Class Reference
MePolyRedistributePtsCurvatureUnitTests Class Reference
Class for testing MePolyRedistributePtsCurvature.
#include <MePolyRedistributePtsCurvature.t.h>
Public Member Functions
void testCreateClass ()
tests creating the class
void testSetup ()
tests a simple case shown below
void testGetSignificantPoints ()
tests a simple case shown below
void testCalculateCurvature ()
tests a simple case shown below
void testShiftAndAggregateOpen ()
tests a simple case shown below
void testShiftAndAggregateClosed ()
tests a simple case shown below
void testDoSmoothing ()
tests a simple case shown below
void testNewPointsFromParamCurvs ()
tests a simple case shown below
Detailed Description
Class for testing MePolyRedistributePtsCurvature.
Definition at line 29 of file MePolyRedistributePtsCurvature.t.h.
Member Function Documentation
testCalculateCurvature()
void MePolyRedistributePtsCurvatureUnitTests::testCalculateCurvature ()
tests a simple case shown below
        2       4-5
      /   \   /    \
    1       3       \
  /                  \
0                     6
Definition at line 636 of file MePolyRedistributePtsCurvature.cpp.
References xms::MePolyRedistributePtsCurvatureImpl::CalculateCurvature(), xms::MePolyRedistributePtsCurvatureImpl::GetSignificantPoints(), xms::MePolyRedistributePtsCurvatureImpl::m_curvature, xms::MePolyRedistributePtsCurvatureImpl::m_parametricDistance, xms::MePolyRedistributePtsCurvatureImpl::Setup(), and TS_ASSERT_DELTA_VEC.
testDoSmoothing()
void MePolyRedistributePtsCurvatureUnitTests::testDoSmoothing ()
tests a simple case shown below
        2       4-5
      /   \   /    \
    1       3       \
  /                  \
0                     6
Definition at line 752 of file MePolyRedistributePtsCurvature.cpp.
References xms::MePolyRedistributePtsCurvatureImpl::CalculateCurvature(), xms::MePolyRedistributePtsCurvatureImpl::DoSmoothing(), xms::MePolyRedistributePtsCurvatureImpl::GetSignificantPoints(), xms::MePolyRedistributePtsCurvatureImpl::m_curvature, xms::MePolyRedistributePtsCurvatureImpl::m_parametricDistance, xms::MePolyRedistributePtsCurvatureImpl::Setup(), xms::MePolyRedistributePtsCurvatureImpl::ShiftAndAggregateOpen(), and TS_ASSERT_DELTA_VEC.
testGetSignificantPoints()
void MePolyRedistributePtsCurvatureUnitTests::testGetSignificantPoints ()
tests a simple case shown below
        2       4
      /   \   /   \
    1       3      \
  /                 \
0                    5
Definition at line 607 of file MePolyRedistributePtsCurvature.cpp.
References xms::MePolyRedistributePtsCurvatureImpl::GetSignificantPoints(), xms::MePolyRedistributePtsCurvatureImpl::m_curvature, xms::MePolyRedistributePtsCurvatureImpl::m_parametricDistance, xms::MePolyRedistributePtsCurvatureImpl::Setup(), and TS_ASSERT_DELTA_VEC.
testNewPointsFromParamCurvs()
void MePolyRedistributePtsCurvatureUnitTests::testNewPointsFromParamCurvs ()
tests a simple case shown below
        2       4-5
      /   \   /    \
    1       3       \
  /                  \
0                     6
Definition at line 788 of file MePolyRedistributePtsCurvature.cpp.
References xms::MePolyRedistributePtsCurvatureImpl::CalculateCurvature(), xms::MePolyRedistributePtsCurvatureImpl::DoSmoothing(), xms::MePolyRedistributePtsCurvatureImpl::GetSignificantPoints(), xms::MePolyRedistributePtsCurvatureImpl::NewPointsFromParamCurvs(), xms::MePolyRedistributePtsCurvatureImpl::Setup(), xms::MePolyRedistributePtsCurvatureImpl::ShiftAndAggregateClosed(), xms::MePolyRedistributePtsCurvatureImpl::ShiftAndAggregateOpen(), and TS_ASSERT_DELTA_VECPT3D.
testSetup()
void MePolyRedistributePtsCurvatureUnitTests::testSetup ()
tests a simple case shown below
        2       4
      /   \   /   \
    1       3      \
  /                 \
0                    5
Definition at line 543 of file MePolyRedistributePtsCurvature.cpp.
References xms::MePolyRedistributePtsCurvatureImpl::m_accumulatedSegmentLengths, xms::MePolyRedistributePtsCurvatureImpl::m_curvature, xms::MePolyRedistributePtsCurvatureImpl::m_length, xms::MePolyRedistributePtsCurvatureImpl::m_open, xms::MePolyRedistributePtsCurvatureImpl::m_parametricDistance, xms::MePolyRedistributePtsCurvatureImpl::m_points, xms::MePolyRedistributePtsCurvatureImpl::m_segmentLengths, xms::MePolyRedistributePtsCurvatureImpl::m_tol, xms::MePolyRedistributePtsCurvatureImpl::Setup(), and TS_ASSERT_DELTA_VEC.
testShiftAndAggregateClosed()
void MePolyRedistributePtsCurvatureUnitTests::testShiftAndAggregateClosed ()
tests a simple case shown below
        2       4-5
      /   \   /    \
    1       3       \
  /                  \
0                     6
Definition at line 717 of file MePolyRedistributePtsCurvature.cpp.
References xms::MePolyRedistributePtsCurvatureImpl::CalculateCurvature(), xms::MePolyRedistributePtsCurvatureImpl::GetSignificantPoints(), xms::MePolyRedistributePtsCurvatureImpl::m_curvature, xms::MePolyRedistributePtsCurvatureImpl::m_parametricDistance, xms::MePolyRedistributePtsCurvatureImpl::Setup(), xms::MePolyRedistributePtsCurvatureImpl::ShiftAndAggregateClosed(), and TS_ASSERT_DELTA_VEC.
testShiftAndAggregateOpen()
void MePolyRedistributePtsCurvatureUnitTests::testShiftAndAggregateOpen ()
tests a simple case shown below
        2       4-5
      /   \   /    \
    1       3       \
  /                  \
0                     6
Definition at line 683 of file MePolyRedistributePtsCurvature.cpp.
References xms::MePolyRedistributePtsCurvatureImpl::CalculateCurvature(), xms::MePolyRedistributePtsCurvatureImpl::GetSignificantPoints(), xms::MePolyRedistributePtsCurvatureImpl::m_curvature, xms::MePolyRedistributePtsCurvatureImpl::m_parametricDistance, xms::MePolyRedistributePtsCurvatureImpl::Setup(), xms::MePolyRedistributePtsCurvatureImpl::ShiftAndAggregateOpen(), and TS_ASSERT_DELTA_VEC.
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/meshing/detail/MePolyRedistributePtsCurvature.t.h
/home/conan/xmsmesh/meshing/detail/MePolyRedistributePtsCurvature.cpp