xmsmesh: MeMultiPolyMesherUnitTests Class Reference
MeMultiPolyMesherUnitTests Class Reference
Tests for MeMultiPolyMesher.
Public Member Functions
void testCreateClass ()
tests creating the class
void testCheckForIntersections1 ()
Tests checking for bad input: self-intersecting outer poly.
void testCheckForIntersections2 ()
Tests checking for bad input: self-intersecting inner poly.
void testCheckForIntersections3 ()
Tests checking for bad input: inner poly intersects outer poly.
void testCheckForIntersections4 ()
Tests checking for bad input: 2 outer polys overlap.
void testCheckForIntersections5 ()
Tests checking for bad input: 2 inner polys overlap.
Detailed Description
Tests for MeMultiPolyMesher.
Definition at line 23 of file MeMultiPolyMesher.t.h.
Member Function Documentation
testCheckForIntersections1()
void MeMultiPolyMesherUnitTests::testCheckForIntersections1 ()
Tests checking for bad input: self-intersecting outer poly.
///              10              *
///                            / |
///               0    *----/----*
///                    | /
///             -10    *
///                    0--------100
///
Definition at line 830 of file MeMultiPolyMesher.cpp.
References xms::XmLog::GetAndClearStackStr(), Singleton< XmLog >::Instance(), xms::MeMultiPolyMesherIo::m_checkTopology, xms::MePolyInput::m_outPoly, xms::MeMultiPolyMesherIo::m_polys, xms::MeMultiPolyMesher::New(), and xmAsserting().
testCheckForIntersections2()
void MeMultiPolyMesherUnitTests::testCheckForIntersections2 ()
Tests checking for bad input: self-intersecting inner poly.
///             100    *-------------*
///                    |           * |
///                    |         / | |
///                    | *----/----* |
///                    | | /         |
///                    | *           |
///               0    *-------------*
///                    0------------100
///
Definition at line 868 of file MeMultiPolyMesher.cpp.
References xms::XmLog::GetAndClearStackStr(), Singleton< XmLog >::Instance(), xms::MeMultiPolyMesherIo::m_checkTopology, xms::MePolyInput::m_insidePolys, xms::MePolyInput::m_outPoly, xms::MeMultiPolyMesherIo::m_polys, xms::MeMultiPolyMesher::New(), and xmAsserting().
testCheckForIntersections3()
void MeMultiPolyMesherUnitTests::testCheckForIntersections3 ()
Tests checking for bad input: inner poly intersects outer poly.
///             100    *-------------*
///                    |             |
///                    |          *--|--*
///                    |          |  |  |
///                    |          *--|--*
///               0    *-------------*
///                    0------------100
///
Definition at line 907 of file MeMultiPolyMesher.cpp.
References xms::XmLog::GetAndClearStackStr(), Singleton< XmLog >::Instance(), xms::MeMultiPolyMesherIo::m_checkTopology, xms::MePolyInput::m_insidePolys, xms::MePolyInput::m_outPoly, xms::MeMultiPolyMesherIo::m_polys, xms::MeMultiPolyMesher::New(), and xmAsserting().
testCheckForIntersections4()
void MeMultiPolyMesherUnitTests::testCheckForIntersections4 ()
Tests checking for bad input: 2 outer polys overlap.
///                      *-------------*
///             100    *-|-----------* |
///                    | |           | |
///                    | |           | |
///                    | |           | |
///                    | |           | |
///                    | *-------------*
///               0    *-------------*
///                    0------------100
///
Definition at line 951 of file MeMultiPolyMesher.cpp.
References xms::XmLog::GetAndClearStackStr(), Singleton< XmLog >::Instance(), xms::MeMultiPolyMesherIo::m_checkTopology, xms::MePolyInput::m_outPoly, xms::MeMultiPolyMesherIo::m_polys, xms::MeMultiPolyMesher::New(), and xmAsserting().
testCheckForIntersections5()
void MeMultiPolyMesherUnitTests::testCheckForIntersections5 ()
Tests checking for bad input: 2 inner polys overlap.
///             100-   *--------------*
///                    |    *-----*   |
///                    |  *-|---* |   |
///                    |  | |   | |   |
///                    |  | *-----*   |
///                    |  *-----*     |
///               0-   *--------------*
///
///                    0------------100
///
Definition at line 994 of file MeMultiPolyMesher.cpp.
References xms::XmLog::GetAndClearStackStr(), Singleton< XmLog >::Instance(), xms::MeMultiPolyMesherIo::m_checkTopology, xms::MePolyInput::m_insidePolys, xms::MePolyInput::m_outPoly, xms::MeMultiPolyMesherIo::m_polys, xms::MeMultiPolyMesher::New(), and xmAsserting().
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/meshing/MeMultiPolyMesher.t.h
/home/conan/xmsmesh/meshing/MeMultiPolyMesher.cpp