xmsmesh: xms::MeQuadBlossom Class Reference
xms::MeQuadBlossom Class Reference
Class to convert 2D grid of triangles to quads.
Public Member Functions
MeQuadBlossom ()
Constructor.
virtual ~MeQuadBlossom ()
Destructor.
Static Public Member Functions
static BSHP< MeQuadBlossom > New (BSHP< XmUGrid > a_ugrid)
Create new MeQuadBlossom.
static double EstimatedRunTimeInMinutes (int a_numPoints)
Get the estimated time to run the Quad Blossom algorithm in minutes.
static BSHP< XmUGrid > SplitToQuads (BSHP< XmUGrid > a_ugrid)
Splits UGrid with 2D cells into quads by adding midpoints for each edge and creating a quad by attaching adjacent midsides to the centroid.
Detailed Description
Class to convert 2D grid of triangles to quads.
See also
MeQuadBlossomImpl
Definition at line 34 of file MeQuadBlossom.h.
Member Function Documentation
EstimatedRunTimeInMinutes()
double xms::MeQuadBlossom::EstimatedRunTimeInMinutes (int a_numPoints) static
Get the estimated time to run the Quad Blossom algorithm in minutes.
Parameters
[in] a_numPoints The number of mesh points.
Returns
The estimated minutes to generate the quad mesh.
Definition at line 949 of file MeQuadBlossom.cpp.
Referenced by TutMeshingIntermediateTests::test_Example_QuadBlossom_BadQuadRemover(), and MeQuadBlossomUnitTests::testEstimatedRunTime().
New()
BSHP< MeQuadBlossom > xms::MeQuadBlossom::New (BSHP< XmUGrid > a_ugrid) static
Create new MeQuadBlossom.
Parameters
[in] a_ugrid The UGrid to be converted from triangles to quads.
Returns
The new MeQuadBlossom.
Definition at line 925 of file MeQuadBlossom.cpp.
Referenced by TutMeshingIntermediateTests::test_Example_QuadBlossom_BadQuadRemover().
SplitToQuads()
BSHP< XmUGrid > xms::MeQuadBlossom::SplitToQuads (BSHP< XmUGrid > a_ugrid) static
Splits UGrid with 2D cells into quads by adding midpoints for each edge and creating a quad by attaching adjacent midsides to the centroid.
Parameters
[in] a_ugrid The input UGrid that contains only 2D cells.
Returns
The UGrid with cells split into quads.
centroidIdx -------— midside | | midsideLast ---------— currentIdx
Definition at line 960 of file MeQuadBlossom.cpp.
References gmComputeCentroid(), and xms::XmUGrid::New().
Referenced by MeQuadBlossomUnitTests::testSplitToQuads().
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/meshing/detail/MeQuadBlossom.h
/home/conan/xmsmesh/meshing/detail/MeQuadBlossom.cpp