xmsmesh: xms::MeRefinePtsToPolys Class Reference
xms::MeRefinePtsToPolys Class Reference
Creates polygon from refine point information.
#include <MeRefinePtsToPolys.h>
Static Public Member Functions
static BSHP< MeRefinePtsToPolys > New ()
Creates a new instance of this class.
Detailed Description
Creates polygon from refine point information.
See also
MeRefinePtsToPolysImpl
Definition at line 28 of file MeRefinePtsToPolys.h.
Member Function Documentation
New()
BSHP< MeRefinePtsToPolys > xms::MeRefinePtsToPolys::New () static
Creates a new instance of this class.
Returns
MeRefinePtsToPolys.
Definition at line 101 of file MeRefinePtsToPolys.cpp.
Referenced by xms::MePolyMesherImpl::MeshIt(), xms::MePolyMesher::New(), and MeRefinePtsToPolysUnitTests::testCreateClass().
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/meshing/detail/MeRefinePtsToPolys.h
/home/conan/xmsmesh/meshing/detail/MeRefinePtsToPolys.cpp