xmsmesh: MeMeshUtilsUnitTests Class Reference
MeMeshUtilsUnitTests Class Reference
Unit tests for MeMeshUtils.
Public Member Functions
void testSizeFuncFromDepth ()
Tests creating a size function from depth.
void testSmoothSizeFunc ()
Tests size function smoothing.
void testSmoothSizeFunc1 ()
[snip_MeMeshUtilsTests::testSmoothSizeFunc]
void testSmoothSizeFunc2 ()
[snip_MeMeshUtilsTests::testSmoothSizeFunc1]
void testSmoothSizeFunc3 ()
[snip_MeMeshUtilsTests::testSmoothSizeFunc2]
Detailed Description
Unit tests for MeMeshUtils.
Definition at line 21 of file MeMeshUtils.t.h.
Member Function Documentation
testSmoothSizeFunc()
void MeMeshUtilsUnitTests::testSmoothSizeFunc ()
Tests size function smoothing.
/// Input
///
///       100     100     100      100
///  20- *[8]    *[9]     *[10]    *[11]
///    |
///    |
///    |  1       100      100      100
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  100     100      100      100
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
/// Output
///
///       4.4     7.9     11.3      14.8
///  20- *[8]    *[9]     *[10]    *[11]
///    |
///    |
///    |  1       4.4      7.9      11.3
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  4.4     5.9      9.3       12.8
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
[snip_MeMeshUtilsTests::testSmoothSizeFunc]
Definition at line 451 of file MeMeshUtils.cpp.
References xms::TrTin::New(), xms::TrTriangulator::Triangulate(), and TS_ASSERT_DELTA_VEC.
testSmoothSizeFunc1()
void MeMeshUtilsUnitTests::testSmoothSizeFunc1 ()
[snip_MeMeshUtilsTests::testSmoothSizeFunc]
Tests size function smoothing
/// Input
///
///       1        1        1        1
///  20- *[8]     *[9]     *[10]    *[11]
///    |
///    |
///    |  100      1        1        1
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  1        1        1        1
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
/// Output
///
///       95.5     96.5     89.6     86.1
///  20- *[8]     *[9]     *[10]    *[11]
///    |
///    |
///    |  100      96.5     93.0     89.6
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  95.5    95.0     91.6      88.1
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
[snip_MeMeshUtilsTests::testSmoothSizeFunc1]
Definition at line 506 of file MeMeshUtils.cpp.
References xms::TrTin::New(), xms::TrTriangulator::Triangulate(), and TS_ASSERT_DELTA_VEC.
testSmoothSizeFunc2()
void MeMeshUtilsUnitTests::testSmoothSizeFunc2 ()
[snip_MeMeshUtilsTests::testSmoothSizeFunc1]
Tests size function smoothing
/// Input
///
///       100     100     100      100
///  20- *[8]    *[9]     *[10]    *[11]
///    |
///    |
///    |  1       100      100      100
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  100     100      100      100
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
/// Output
///
///       6.0    11.0     16.0      21.0
///  20- *[8]    *[9]     *[10]    *[11]
///    |
///    |
///    |  1       6.0     11.0      16.0
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  6.0     8.0     13.0       18.0
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
[snip_MeMeshUtilsTests::testSmoothSizeFunc2]
Definition at line 562 of file MeMeshUtils.cpp.
References xms::TrTin::New(), xms::TrTriangulator::Triangulate(), and TS_ASSERT_DELTA_VEC.
testSmoothSizeFunc3()
void MeMeshUtilsUnitTests::testSmoothSizeFunc3 ()
[snip_MeMeshUtilsTests::testSmoothSizeFunc2]
Tests size function smoothing
/// Input
///
///       1        1        1        1
///  20- *[8]     *[9]     *[10]    *[11]
///    |
///    |
///    |  100      1        1        1
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  1        1        1        1
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
/// Output
///
///       95.0     90.0     85.0     80.0
///  20- *[8]     *[9]     *[10]    *[11]
///    |
///    |
///    |  100      95.0     90.0     85.0
///  10- *[4]     *[5]     *[6]     *[7]
///    |
///    |
///    |  95.0    92.9     87.9      82.9
///   0- *[0]     *[1]     *[2]     *[3]
///      0-------10-------20-------30
///
[snip_MeMeshUtilsTests::testSmoothSizeFunc3]
Definition at line 617 of file MeMeshUtils.cpp.
References xms::TrTin::New(), xms::TrTriangulator::Triangulate(), and TS_ASSERT_DELTA_VEC.
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/meshing/MeMeshUtils.t.h
/home/conan/xmsmesh/meshing/MeMeshUtils.cpp