xmsmesh: TutRedistributionIntermediateTests Class Reference
TutRedistributionIntermediateTests Class Reference
Class for testing polyline/polygon point redistribution.
#include <TutMeshing.t.h>
Public Member Functions
void test_Example_SimplePolygon_Redistribute ()
[snip_test_Example_SpringRelax]
void test_Example_Redistribute_SizeFunction ()
[snip_test_example_SimplePolygon_Redistribute]
void test_Example_Redistribute_Curvature ()
[snip_test_Example_Redistribute_SizeFunction]
void test_Example_Redistribute_Polygon_Curvature ()
[test_Example_Redistribute_Curvature]
Detailed Description
Class for testing polyline/polygon point redistribution.
Definition at line 54 of file TutMeshing.t.h.
Member Function Documentation
test_Example_Redistribute_Curvature()
void TutRedistributionIntermediateTests::test_Example_Redistribute_Curvature ()
[snip_test_Example_Redistribute_SizeFunction]
Example for redistributing a polyline using curvature. [test_Example_Redistribute_Curvature]
Definition at line 886 of file TutMeshing.cpp.
References xms::MePolyRedistributePts::New(), and TS_ASSERT_DELTA_VECPT3D.
test_Example_Redistribute_Polygon_Curvature()
void TutRedistributionIntermediateTests::test_Example_Redistribute_Polygon_Curvature ()
[test_Example_Redistribute_Curvature]
Example for redistributing a polyline using curvature. [test_Example_Redistribute_Polygon_Curvature]
Definition at line 928 of file TutMeshing.cpp.
References xms::MePolyRedistributePts::New(), and TS_ASSERT_DELTA_VECPT3D.
test_Example_Redistribute_SizeFunction()
void TutRedistributionIntermediateTests::test_Example_Redistribute_SizeFunction ()
[snip_test_example_SimplePolygon_Redistribute]
Example for redistributing a polygon using scalar paving. [snip_test_Example_Redistribute_SizeFunction]
Definition at line 822 of file TutMeshing.cpp.
References xms::InterpLinear::New(), xms::MePolyRedistributePts::New(), and TS_ASSERT_DELTA_VECPT3D.
test_Example_SimplePolygon_Redistribute()
void TutRedistributionIntermediateTests::test_Example_SimplePolygon_Redistribute ()
[snip_test_Example_SpringRelax]
Example for redistributing points on a polygon boundary to a constant spacing. [snip_test_example_SimplePolygon_Redistribute]
Definition at line 792 of file TutMeshing.cpp.
References xms::MePolyRedistributePts::New(), and TS_ASSERT_DELTA_VECPT3D.
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/tutorial/TutMeshing.t.h
/home/conan/xmsmesh/tutorial/TutMeshing.cpp