xmsmesh: xms::MePolyPts Class Reference
xms::MePolyPts Class Reference
Utility class to work with polygon paving.
#include <MePolyPts.h>
Classes
class impl
Implementation of MePolyPts.
Public Member Functions
MePolyPts ()
constructor
double & XyTol ()
Returns the tolerance.
std::vector< Pt3d > & Pts ()
Returns the vector of points.
BSHP< std::vector< Pt3d > > PtsSharedPointer ()
Returns the vector of points.
std::vector< size_t > HashPts ()
Hashes the point locations.
std::vector< size_t > SegmentsForCleanPolyOffset ()
Returns the segments that will be used in CleanPolyOffset.
void IntersectSegs (const std::vector< size_t > &a_segs)
Intersects the segments.
std::list< size_t > SequenceWithIntersects (std::vector< size_t > &a_segs)
Returns a new sequence that includes intersection indexes.
void CheckIntersectTwoSegs (size_t a_i, size_t a_j, const std::vector< size_t > &a_iSeg, const std::vector< size_t > &a_jSeg)
Intersects 2 segments.
void CalcLoopsForCleanPolyOffset (std::list< size_t > &a_sequence, std::list< std::vector< size_t >> &a_loops)
Calculates new loops from a sequence that has intersections included.
void RemoveBackwardLoopsForCleanPolyOffset (std::list< std::vector< size_t >> &a_loops, int a_pType)
Removes loops that are "backwards" for CleanPolyOffset. "backwards" depends on the type of input (OUTSIDE_POLY or INSIDE_POLY)
void ClassifyLoopsFromInPolyAndRemoveInvalid (std::list< std::vector< size_t >> &a_loops, std::vector< int > &a_loopType)
Classifies loops extracted from a pave on an INSIDE_POLY and removes invalid loops. There are more rules when dealing with paving outward from polygons. Sometimes paving outward will create a new "outside" polygon that we then pave inward on the next step in the algorithm. See testCase8. You can also generate "inside" polygons that are inside of other "inside" polygons. These are deleted. Again see testCase8.
bool PolyInsideOfPoly (const std::vector< size_t > &a_poly, const std::vector< size_t > &a_polyToTest)
Returns true if a_polyToTest is inside of a_poly.
bool PolyInsideOfPoly (const std::vector< Pt3d > &a_poly, const std::vector< size_t > &a_polyToTest)
Returns true if a_polyToTest is inside of a_poly.
size_t IdxFromPt3d (const Pt3d &a_pt)
Returns the index of a location by hashing that location with the current list of points. If the location does not exist yet then it is added to the list of points.
Private Attributes
BSHP< impl > m_p
implementation class
Detailed Description
Utility class to work with polygon paving.
Helper class used by PolyCleaner.
Definition at line 29 of file MePolyPts.h.
Member Function Documentation
void xms::MePolyPts::CalcLoopsForCleanPolyOffset (std::list< size_t > & a_sequence, std::list< std::vector< size_t >> & a_loops)
Calculates new loops from a sequence that has intersections included.
Parameters
a_sequence List of indexes defining a closed loop polyline. If the polyline intersects with itself then multiple loops are extracted from the polyline.
a_loops List of vector of indexes defining a closed loop polyline. These are extracted from a_sequence
Definition at line 677 of file MePolyPts.cpp.
Referenced by xms::MePolyCleanerImpl::CleanPolyOffset().
void xms::MePolyPts::CheckIntersectTwoSegs (size_t a_i, size_t a_j, const std::vector< size_t > & a_iSeg, const std::vector< size_t > & a_jSeg)
Intersects 2 segments.
Parameters
a_i Index to a segment.
a_j Index to a segment.
a_iSeg Vector of indexes defining a closed loop polyline referred to by a_i
a_jSeg Vector of indexes defining a closed loop polyline referred to by a_j
Definition at line 662 of file MePolyPts.cpp.
References m_p, and XyTol().
Referenced by IntersectSegs().
void xms::MePolyPts::ClassifyLoopsFromInPolyAndRemoveInvalid (std::list< std::vector< size_t >> & a_loops, std::vector< int > & a_loopType)
Classifies loops extracted from a pave on an INSIDE_POLY and removes invalid loops. There are more rules when dealing with paving outward from polygons. Sometimes paving outward will create a new "outside" polygon that we then pave inward on the next step in the algorithm. See testCase8. You can also generate "inside" polygons that are inside of other "inside" polygons. These are deleted. Again see testCase8.
Parameters
a_loops List of vector of indexes defining a closed loop polyline.
a_loopType Type of polygon defined in a_loops.
Definition at line 751 of file MePolyPts.cpp.
References Pts().
Referenced by xms::MePolyCleanerImpl::CleanPolyOffset().
std::vector< size_t > xms::MePolyPts::HashPts ()
Hashes the point locations.
Returns
Vector of new indexes for points.
Definition at line 580 of file MePolyPts.cpp.
References PtsSharedPointer(), and XyTol().
Referenced by SegmentsForCleanPolyOffset().
size_t xms::MePolyPts::IdxFromPt3d (const Pt3d & a_pt)
Returns the index of a location by hashing that location with the current list of points. If the location does not exist yet then it is added to the list of points.
Parameters
a_pt A location.
Returns
index for a_pt.
Definition at line 851 of file MePolyPts.cpp.
References m_p.
void xms::MePolyPts::IntersectSegs (const std::vector< size_t > & a_segs)
Intersects the segments.
Parameters
a_segs Vector of indexes defining segments.
Definition at line 608 of file MePolyPts.cpp.
References CheckIntersectTwoSegs(), and Pts().
Referenced by xms::MePolyCleanerImpl::CleanPolyOffset().
bool xms::MePolyPts::PolyInsideOfPoly (const std::vector< size_t > & a_poly, const std::vector< size_t > & a_polyToTest)
Returns true if a_polyToTest is inside of a_poly.
Parameters
a_poly A polygon used to test a_polyToTest
a_polyToTest Vector of indices defining a polygon. Want to determine if it is inside of a_poly.
Returns
true if a_polyToText is inside of a_poly
Definition at line 812 of file MePolyPts.cpp.
References Pts().
bool xms::MePolyPts::PolyInsideOfPoly (const std::vector< Pt3d > & a_poly, const std::vector< size_t > & a_polyToTest)
Returns true if a_polyToTest is inside of a_poly.
Parameters
a_poly Vector of points defining a polygon. 1st point repeated at the end of the vector.
a_polyToTest Vector of indices defining a polygon. Want to determine if it is inside of a_poly.
Returns
true if a_polyToText is inside of a_poly
Definition at line 833 of file MePolyPts.cpp.
References Pts().
std::vector< Pt3d > & xms::MePolyPts::Pts ()
Returns the vector of points.
Returns
The vector of points.
Definition at line 564 of file MePolyPts.cpp.
References m_p.
Referenced by xms::MeIntersectPolys::CalcEnvelopes(), ClassifyLoopsFromInPolyAndRemoveInvalid(), xms::MePolyCleanerImpl::CleanPolyOffset(), IntersectSegs(), PolyInsideOfPoly(), RemoveBackwardLoopsForCleanPolyOffset(), SegmentsForCleanPolyOffset(), and xms::MeIntersectPolys::impl::SetupInIn().
BSHP< std::vector< Pt3d > > xms::MePolyPts::PtsSharedPointer ()
Returns the vector of points.
Returns
Shared pointer to vector of points.
Definition at line 572 of file MePolyPts.cpp.
References m_p.
Referenced by HashPts().
void xms::MePolyPts::RemoveBackwardLoopsForCleanPolyOffset (std::list< std::vector< size_t >> & a_loops, int a_pType)
Removes loops that are "backwards" for CleanPolyOffset. "backwards" depends on the type of input (OUTSIDE_POLY or INSIDE_POLY)
Parameters
a_loops List of vector of indexes defining a closed loop polyline.
a_pType Type of polygon that was offset either OUTSIDE_POLY or INSIDE_POLY.
Definition at line 723 of file MePolyPts.cpp.
References Pts().
Referenced by xms::MePolyCleanerImpl::CleanPolyOffset().
std::vector< size_t > xms::MePolyPts::SegmentsForCleanPolyOffset ()
Returns the segments that will be used in CleanPolyOffset.
Returns
Segments that will be used in CleanPolyOffset.
Definition at line 590 of file MePolyPts.cpp.
References HashPts(), and Pts().
Referenced by xms::MePolyCleanerImpl::CleanPolyOffset().
std::list< size_t > xms::MePolyPts::SequenceWithIntersects (std::vector< size_t > & a_segs)
Returns a new sequence that includes intersection indexes.
Parameters
a_segs List of indexes defining a closed loop polyline.
Returns
a new sequence
Definition at line 630 of file MePolyPts.cpp.
References m_p.
Referenced by xms::MePolyCleanerImpl::CleanPolyOffset().
double & xms::MePolyPts::XyTol ()
Returns the tolerance.
Returns
the xy tolerance.
Definition at line 556 of file MePolyPts.cpp.
References m_p.
Referenced by CheckIntersectTwoSegs(), xms::MePolyCleanerImpl::CleanPolyOffset(), HashPts(), and xms::MeIntersectPolys::impl::SetupInIn().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmsmesh/xmsmesh/meshing/detail/MePolyPts.h
/home/travis/build/Aquaveo/xmsmesh/xmsmesh/meshing/detail/MePolyPts.cpp