xmsmesh: xms::MeBadQuadRemover Class Reference
xms::MeBadQuadRemover Class Reference
Public Member Functions
MeBadQuadRemover ()
Constructor.
virtual ~MeBadQuadRemover ()
Destructor.
Static Public Member Functions
static BSHP< MeBadQuadRemover > New (BSHP< XmUGrid > a_ugrid)
Create new MeBadQuadRemover.
Detailed Description
See also
MeBadQuadRemoverImpl
Definition at line 34 of file MeBadQuadRemover.h.
Member Function Documentation
New()
BSHP< MeBadQuadRemover > xms::MeBadQuadRemover::New (BSHP< XmUGrid > a_ugrid) static
Create new MeBadQuadRemover.
Parameters
[in] a_ugrid The UGrid to remove badly formed quads from.
Returns
The new MeBadQuadRemover.
Definition at line 610 of file MeBadQuadRemover.cpp.
Referenced by TutMeshingIntermediateTests::test_Example_QuadBlossom_BadQuadRemover(), MeBadQuadRemoverUnitTests::testCollapse(), and MeBadQuadRemoverUnitTests::testCollapseQuadTri().
The documentation for this class was generated from the following files:
/home/conan/xmsmesh/meshing/detail/MeBadQuadRemover.h
/home/conan/xmsmesh/meshing/detail/MeBadQuadRemover.cpp