xmsmesh: xms::MeMultiPolyTo2dmImpl Class Reference
xms::MeMultiPolyTo2dmImpl Class Reference
Creates a VTK Unstructured Grid from polygons.
Public Member Functions
bool Generate2dm (MeMultiPolyMesherIo &a_input, const std::string &a_outFileName, int a_precision=15) override
Creates a 2dm file from polygons.
bool Generate2dm (MeMultiPolyMesherIo &a_input, std::ostream &a_os, int a_precision=15) override
Creates a 2dm file from polygons by meshing.
void Write2dm (MeMultiPolyMesherIo &a_input, std::ostream &a_os, int a_precision)
Writes 2dm data from a point and cell stream from the MeMultiPolyMesherIo class.
virtual void SetObserver (BSHP< Observer > a_) override
sets the observer class to give feedback on the grid generation process
Public Attributes
BSHP< Observer > m_prog
observer class to give feedback on grid generation process
bool m_sortCellsForTesting = true
Additional Inherited Members
Static Public Member Functions inherited from xms::MeMultiPolyTo2dm
static boost::shared_ptr
< MeMultiPolyTo2dm > New ()
Creates a class.
Detailed Description
Creates a VTK Unstructured Grid from polygons.
Definition at line 50 of file MeMultiPolyTo2dm.cpp.
Member Function Documentation
bool xms::MeMultiPolyTo2dmImpl::Generate2dm (MeMultiPolyMesherIo & a_io, const std::string & a_outFileName, int a_precision = 15) override
Creates a 2dm file from polygons.
Parameters
[in] a_io Input/output of polygons and options for generating a mesh.
[in] a_outFileName output filename
[in] a_precision pinted digits of precision of points in file
Returns
true if the mesh was generated.
Definition at line 154 of file MeMultiPolyTo2dm.cpp.
Referenced by MeMultiPolyTo2dmUnitTests::testCase4(), and MeMultiPolyTo2dmIntermediateTests::testCasePatch6().
bool xms::MeMultiPolyTo2dmImpl::Generate2dm (MeMultiPolyMesherIo & a_io, std::ostream & a_os, int a_precision = 15) override
Creates a 2dm file from polygons by meshing.
Parameters
[in] a_io Input/output of polygons and options for generating a mesh.
[in] a_os output stream to store the mesh
[in] a_precision pinted digits of precision of points in file
Returns
true if a mesh was created
Definition at line 169 of file MeMultiPolyTo2dm.cpp.
References xmlog::error, m_prog, xms::MeMultiPolyMesher::New(), Write2dm(), and XM_LOG.
virtual void xms::MeMultiPolyTo2dmImpl::SetObserver (BSHP< Observer > a_) inline override virtual
sets the observer class to give feedback on the grid generation process
Parameters
a_ The observer.
Definition at line 66 of file MeMultiPolyTo2dm.cpp.
References m_prog.
void xms::MeMultiPolyTo2dmImpl::Write2dm (MeMultiPolyMesherIo & a_io, std::ostream & a_os, int a_precision)
Writes 2dm data from a point and cell stream from the MeMultiPolyMesherIo class.
Parameters
[in] a_io Input/output of polygons and options for generating a mesh.
[in] a_os output stream to store the mesh
[in] a_precision pinted digits of precision of points in file
Definition at line 198 of file MeMultiPolyTo2dm.cpp.
References xms::MeMultiPolyMesherIo::m_cells, xms::MeMultiPolyMesherIo::m_points, m_sortCellsForTesting, xms::STR_FULLWIDTH, xms::STRstd(), xms::Pt3< T >::x, XM_ENSURE_TRUE_NO_ASSERT, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by Generate2dm().
Member Data Documentation
bool xms::MeMultiPolyTo2dmImpl::m_sortCellsForTesting = true
to avoid different order of cells/elements on different OS'es we will sort the cells for consistent results
Definition at line 72 of file MeMultiPolyTo2dm.cpp.
Referenced by Write2dm().
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmsmesh/xmsmesh/meshing/MeMultiPolyTo2dm.cpp